name: Lint CloudFormation Templates

on:
  push:
    paths:
    - '**.yaml'
    - '**.yml'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install cfn-lint
      run: |
        pip install cfn-lint

    - name: Run cfn-lint on templates
      run: |
        for file in $(find . -name "*.yaml" -o -name "*.yml"); do
          echo "🔍 Linting $file"
          cfn-lint $file
        done
